name = "mapbus"
main = "src/index.js"
compatibility_date = "2024-01-01"

# Secrets (postavi kroz: wrangler secret put SECRET_NAME)
# GOOGLE_SHEETS_CLIENT_EMAIL
# GOOGLE_SHEETS_PRIVATE_KEY
# GOOGLE_SPREADSHEET_ID
